sessions:
  piquel-fr:
    root: "~/Projects/piquel.fr"
    windows:
    - name: vim
      commands:
        - vim .
    - name: term
      commands:
        - git pull
    - name: server
      commands:
        - deno install
        - deno task dev
  
